name: "Hello World"
description: "Prints Hello World"
author: gipo355
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time: # id of output
    description: "The time we greeted you"
  arg:
    description: "The argument we passed"
runs:
  using: "docker"
  # in repo
  # image: "Dockerfile"
  # in registry.
  image: "Dockerfile"
  # image: "docker://docker.io/halamert/hello-world-docker-go-action"
  # image: "docker://hello-world-docker-go-action"
  args:
    - ${{ inputs.who-to-greet }}
